export const CONFIG_ELEMENT = {
  LOG_LEVEL: 'server:logLevel',
  PORT: 'server:port',
  IAS_TOKEN_ENDPOINT: 'ias:tokenEndpoint',
  IAS_CLIENT_ID: 'ias:clientID',
  IAS_CLIENT_SECRET: 'ias:clientSecret',
  IAS_JWKS_ENDPOINT: 'ias:jwksEndpoint',
  S3_REGION: 's3:region',
  S3_ACCESS_KEY_ID: 's3:accessKeyID',
  S3_SECRET_ACCESS_KEY: 's3:secretAccessKey',
  S3_BUCKET: 's3:bucket',
  JSON_BODY_LIMIT: 'server.bodyLimit',
  MORGAN_FORMAT: 'server:morganFormat',
  ENVIRONMENT: 'environment',
  REDIS_PORT: 'redis:port',
  REDIS_HOST: 'redis:host',
  NATS_URL: 'messaging:natsUrl',
  NATS_MAX_RECONNECT: 'messaging:natsMaxReconnect',
};
